CLOUDFLARE_API_TOKEN="op://Automation and Tools/Cloudflare Token/api_token"
DIGITALOCEAN_TOKEN="op://Automation and Tools/DigitalOcean/api_token"
NAMECHEAP_USER_NAME="op://Automation and Tools/Namecheap/username"
NAMECHEAP_API_USER="op://Automation and Tools/Namecheap/username"
NAMECHEAP_API_KEY="op://Automation and Tools/Namecheap/api_key"
NAMECHEAP_USE_SANDBOX="false"
TF_TOKEN_app_terraform_io="op://Automation and Tools/HCP Terraform/api_token"
